"""added follow and social graph events models

Revision ID: 233e6e44d29e
Revises: c7372482f7db
Create Date: 2025-11-20 20:21:55.653722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233e6e44d29e'
down_revision = 'c7372482f7db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='uq_follower_followee')
    )
    op.create_table('social_graph_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followee_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_graph_events_created_at'), 'social_graph_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_graph_events_followee_id'), 'social_graph_events', ['followee_id'], unique=False)
    op.create_index(op.f('ix_social_graph_events_follower_id'), 'social_graph_events', ['follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_graph_events_follower_id'), table_name='social_graph_events')
    op.drop_index(op.f('ix_social_graph_events_followee_id'), table_name='social_graph_events')
    op.drop_index(op.f('ix_social_graph_events_created_at'), table_name='social_graph_events')
    op.drop_table('social_graph_events')
    op.drop_table('follows')
    # ### end Alembic commands ###