"""add post events models and relationships

Revision ID: 2fbef2f88aec
Revises: 233e6e44d29e
Create Date: 2025-12-02 16:01:14.374541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbef2f88aec'
down_revision = '233e6e44d29e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_version', sa.String(length=16), server_default='v1', nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_events_author_created', 'post_events', ['author_id', 'created_at'], unique=False)
    op.create_index('ix_post_events_type_created', 'post_events', ['event_type', 'created_at'], unique=False)
    op.drop_index('ix_social_graph_events_created_at', table_name='social_graph_events')
    op.drop_index('ix_social_graph_events_followee_id', table_name='social_graph_events')
    op.drop_index('ix_social_graph_events_follower_id', table_name='social_graph_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_social_graph_events_follower_id', 'social_graph_events', ['follower_id'], unique=False)
    op.create_index('ix_social_graph_events_followee_id', 'social_graph_events', ['followee_id'], unique=False)
    op.create_index('ix_social_graph_events_created_at', 'social_graph_events', ['created_at'], unique=False)
    op.drop_index('ix_post_events_type_created', table_name='post_events')
    op.drop_index('ix_post_events_author_created', table_name='post_events')
    op.drop_table('post_events')
    # ### end Alembic commands ###