"""add updated_at to users for consistency

Revision ID: 562ca30cfb1c
Revises: b9bb22f01489
Create Date: 2025-11-19 16:26:24.248234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562ca30cfb1c'
down_revision = 'b9bb22f01489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###