"""added follow and social graph events models

Revision ID: c7372482f7db
Revises: 562ca30cfb1c
Create Date: 2025-11-20 19:39:21.700157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7372482f7db'
down_revision = '562ca30cfb1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###